#operators
a=int(input("Enter the first number a:\n"))
b=int(input("Enter the second number b:\n"))
print("addition of {} and {} is {}".format(a,b,a+b))
print("subraction of {} and {} is {}".format(a,b,a-b))
print("mutliplication of {} and {} is {}".format(a,b,a*b))
print("division of {} and {} is {}".format(a,b,a/b))
print("ground division of {} and {} is {}".format(a,b,a//b))
print("modulo of {} and {} is {}".format(a,b,a%b))
print(" {}power{} is {}".format(a,b,a**b))
print("a is less than b true or false:\n{}".format(a<b))
print("a is greater than b true or false:\n{}".format(a>b))
print("a is equal to b true or false:\n{}".format(a==b))
